### ISSUE TITLE
Ajax calls are pushed in the queue

### ISSUE THREAD

**Issue by dgillier** [ralphjsmit/livewire-urls#13]
I'm using an javascript Ajax call to one of my controller (for a leaflet map popup) and it's pushed in the queue.
So when I'm using the  Url::lastRecorded() function, my json reply is displayed...

Any suggestion ?

Tks, 
Denis

**Comment by ralphjsmit** [comment]
In that case you should ensure that the middleware is only applied on routes that you want the URL to be used for. That means that you should remove it from the `'web'` group in the kernel (if it is in the web group, it will be applied to all normal web requests) and apply it yourself on the routes that you want the urls to be recorded for.
